name: V360
url: https://thev360.github.io
description: V360's projects and blog!

defaults:
  scope:
    path: "blog/"
  values:
    comments: true
    layout: "post"

excerpt_separator: <!--more-->
paginate: 8
paginate_path: "/blog/:num/"
permalink: /blog/:year/:month/:day/:title/
